package com.example.demo.pojo;

import java.util.Date;

public class CuxTodoItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.TODO_ITEM_ID
     *
     * @mbggenerated
     */
    private Long todoItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.TODO_ITEM_TITLE
     *
     * @mbggenerated
     */
    private String todoItemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.TODO_ITEM_CONTENT
     *
     * @mbggenerated
     */
    private String todoItemContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.PRIORITY
     *
     * @mbggenerated
     */
    private String priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.CREATION_DATE
     *
     * @mbggenerated
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cux_todo_items.COMMENTS
     *
     * @mbggenerated
     */
    private String comments;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.TODO_ITEM_ID
     *
     * @return the value of cux_todo_items.TODO_ITEM_ID
     *
     * @mbggenerated
     */
    public Long getTodoItemId() {
        return todoItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.TODO_ITEM_ID
     *
     * @param todoItemId the value for cux_todo_items.TODO_ITEM_ID
     *
     * @mbggenerated
     */
    public void setTodoItemId(Long todoItemId) {
        this.todoItemId = todoItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.USER_ID
     *
     * @return the value of cux_todo_items.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.USER_ID
     *
     * @param userId the value for cux_todo_items.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.TODO_ITEM_TITLE
     *
     * @return the value of cux_todo_items.TODO_ITEM_TITLE
     *
     * @mbggenerated
     */
    public String getTodoItemTitle() {
        return todoItemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.TODO_ITEM_TITLE
     *
     * @param todoItemTitle the value for cux_todo_items.TODO_ITEM_TITLE
     *
     * @mbggenerated
     */
    public void setTodoItemTitle(String todoItemTitle) {
        this.todoItemTitle = todoItemTitle == null ? null : todoItemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.TODO_ITEM_CONTENT
     *
     * @return the value of cux_todo_items.TODO_ITEM_CONTENT
     *
     * @mbggenerated
     */
    public String getTodoItemContent() {
        return todoItemContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.TODO_ITEM_CONTENT
     *
     * @param todoItemContent the value for cux_todo_items.TODO_ITEM_CONTENT
     *
     * @mbggenerated
     */
    public void setTodoItemContent(String todoItemContent) {
        this.todoItemContent = todoItemContent == null ? null : todoItemContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.PRIORITY
     *
     * @return the value of cux_todo_items.PRIORITY
     *
     * @mbggenerated
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.PRIORITY
     *
     * @param priority the value for cux_todo_items.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.CREATION_DATE
     *
     * @return the value of cux_todo_items.CREATION_DATE
     *
     * @mbggenerated
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.CREATION_DATE
     *
     * @param creationDate the value for cux_todo_items.CREATION_DATE
     *
     * @mbggenerated
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.LAST_UPDATE_DATE
     *
     * @return the value of cux_todo_items.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for cux_todo_items.LAST_UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cux_todo_items.COMMENTS
     *
     * @return the value of cux_todo_items.COMMENTS
     *
     * @mbggenerated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cux_todo_items.COMMENTS
     *
     * @param comments the value for cux_todo_items.COMMENTS
     *
     * @mbggenerated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }
}