package com.example.demo.dao;

import com.example.demo.pojo.CuxTodoItems;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CuxTodoItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long todoItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    int insert(CuxTodoItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    int insertSelective(CuxTodoItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    CuxTodoItems selectByPrimaryKey(Long todoItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CuxTodoItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cux_todo_items
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CuxTodoItems record);

    List<Object> selectAll();

}